obstacle_range: 5.0
raytrace_range: 10.0
footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
inflation_radius: 0.3
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: body, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
