local_costmap:
  global_frame: map
  robot_base_frame: body
  update_frequency: 5.0
  publish_frequency: 2.0
  # static_map: true
  static_map: false  #不需要静态地图，可以提升导航效果
  rolling_window: false
  width: 6.0
  height: 6.0
  resolution: 0.05